# Generated by Django 3.0.6 on 2020-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recommended',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
