# Generated by Django 3.0.6 on 2020-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commom', '0002_auto_20200512_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
